### ISSUE TITLE
Build model failed!Error: CUDA out of memory,qwen2.5-3b,应该如何使用多gpu

### ISSUE THREAD

**Issue by xiangzhangpang** [airockchip/rknn-llm#112]
ERROR: Model running Error: CUDA out of memory. Tried to allocate 2.37 GiB. GPU 0 has a total capacty of 23.69 GiB of which 2.03 GiB is free. Process 2693917 has 21.65 GiB memory in use. Of the allocated memory 21.20 GiB is allocated by PyTorch, and 160.05 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF!
WARNING: Please first confirm that the model can run correctly on cuda:0 device!
Build model failed!

**Comment by xiangzhangpang** [comment]
有没有大佬能告诉我该怎么解决这个问题？

**Comment by waydong** [comment]
Tried to allocate 2.37 GiB. GPU 0 has a total capacty of 23.69 GiB of which 2.03 GiB is free，提示可用显存只剩2.03G，转3B模型肯定不够的，目前toolkit只能用一个GPU，你需要指定一个空闲的GPU来转换。

**Comment by xiangzhangpang** [comment]
> Tried to allocate 2.37 GiB. GPU 0 has a total capacty of 23.69 GiB of which 2.03 GiB is free，提示可用显存只剩2.03G，转3B模型肯定不够的，目前toolkit只能用一个GPU，你需要指定一个空闲的GPU来转换。
我用cpu没问题，就是又会有新的报错不知道哪里出问题了

**Comment by waydong** [comment]
killed可能是系统内存不够导致的，你可以先尝试转换一个小点的模型看会不会成功。

**Comment by imkebe** [comment]
Same here. I'm trying to covert 32B model having 98GB or RAM and 55GB of swap... it's killed durring optimisation.

**Comment by c0zaut** [comment]
@imkebe - I'm doing QwQ-preview right now for you - should hopefully be done in a day or two. My server has 2TB of Swap, so hopefully that does the trick lol

**Comment by c0zaut** [comment]
@imkebe 
![image](https://github.com/user-attachments/assets/d20940e5-3d21-4cde-b1d1-5cd28a307dd1)
![image](https://github.com/user-attachments/assets/429b0389-b4d7-404f-b0c9-14a2b8b74b17)

**Comment by LiuJuanXi** [comment]
> > Tried to allocate 2.37 GiB. GPU 0 has a total capacty of 23.69 GiB of which 2.03 GiB is free，提示可用显存只剩2.03G，转3B模型肯定不够的，目前toolkit只能用一个GPU，你需要指定一个空闲的GPU来转换。
> 
> 我用cpu没问题，就是又会有新的报错直接被killed，不知道哪里出问题了

减少量化数据试试
