### ISSUE TITLE
rk3588运行大模型中遇到的多线程推理问题

### ISSUE THREAD

**Issue by danwahe** [airockchip/rknn-llm#315]
rkllm模型转换时设置了NPU核的数量为1（默认使用的npu核是core0），rknn初始化时绑定一个核(core2)，使用rkllm推理时必须要加线程锁，不然线程会卡在推理函数里。然后还发现rknn和rkllm无法同时推理，就没法进行多线程处理，但两个占用的是不同的核。

<img width="1294" height="850" alt="Image" src="https://github.com/user-attachments/assets/272577c2-20c5-432a-bd4e-dbb19552fc38" />

**Comment by hebangwen** [comment]
我也试过 RKLLM 在 npu-0，RKNN 在 npu-1-2 上运行。结果发现 RKLLM 和 RKNN 不能同时执行，否则会出现 `failed to submit ...` 之类的错误，然后系统卡死。

https://github.com/airockchip/rknn-toolkit2/issues/384#issuecomment-3030980163

**Comment by danwahe** [comment]
> 我也试过 RKLLM 在 npu-0，RKNN 在 npu-1-2 上运行。结果发现 RKLLM 和 RKNN 不能同时执行，否则会出现 `failed to submit ...` 之类的错误，然后系统卡死。
> 
> [airockchip/rknn-toolkit2#384 (comment)](https://github.com/airockchip/rknn-toolkit2/issues/384#issuecomment-3030980163)

我是rknn加锁不会系统卡死，但是结果就是其实还是单线程。你目前使用的设备是什么啊，驱动多少，你目前研究到什么地步了，你解决了吗？

**Comment by hebangwen** [comment]
> > 我也试过 RKLLM 在 npu-0，RKNN 在 npu-1-2 上运行。结果发现 RKLLM 和 RKNN 不能同时执行，否则会出现 `failed to submit ...` 之类的错误，然后系统卡死。
> > [airockchip/rknn-toolkit2#384 (comment)](https://github.com/airockchip/rknn-toolkit2/issues/384#issuecomment-3030980163)
> 
> 我是rknn加锁不会系统卡死，但是结果就是其实还是单线程。你目前使用的设备是什么啊，驱动多少，你目前研究到什么地步了，你解决了吗？

报错跟这个比较像，https://github.com/airockchip/rknn-llm/issues/306

3588 rknpu: 0.9.6

没解决呢，所以暂时没用 rkllm 了 😢

**Comment by waydong** [comment]
你好，可以尝试下新版本，解决了部分多线程问题。

**Comment by KaXuan1135** [comment]
你们好，请问你们解决了吗？我目前也遇到同样问题，rkllm 即使限制1个core 也会在推理时导致另一个rknn使用着的 core2 占用率达到 100% 并导致错误。
